var userName = "Mayank";  //String
var userAge = 10;   // Number
var salary = 10.5   // Float
var isEmployeed = false;  // Boolean
var additionalData = null;
var bigInt = 1n;
var data = undefined;
var otherData = NaN;
userName = 10;
